<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query;
/**
 * PdfLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PdfLogRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $personalIdNumbers
     * @param int $hydrationMode
     * @return array|mixed
     */
    public function getRetrievePdf($personalIdNumbers, $hydrationMode = Query::HYDRATE_OBJECT)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb
            ->select('Pdf')
            ->from('AppBundle\Entity\PdfLog', 'Pdf')
            ->where('Pdf.personalIdNumber  IN (:personalIdNumber)')
            ->setParameters([
                'personalIdNumber' => $personalIdNumbers
            ])
        ;

        $query = $qb->getQuery();
        return $query->getResult($hydrationMode);

    }
}
