CREATE TABLE `aegon_pdf` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `personal_id_number` varchar(11) COLLATE utf8_unicode_ci NOT NULL,
  `pol_id` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `policy_number` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `insurance_slug` varchar(128) COLLATE utf8_unicode_ci NOT NULL,
  `pdf_type_slug` varchar(128) COLLATE utf8_unicode_ci NOT NULL,
  `dir_name` varchar(128) COLLATE utf8_unicode_ci NOT NULL,
  `file_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `json_data` longtext COLLATE utf8_unicode_ci,
  `json_processed` longtext COLLATE utf8_unicode_ci,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `moreum_document_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pdf_personal_id_number` (`personal_id_number`),
  KEY `idx_pdf_pol_id` (`pol_id`),
  KEY `idx_pdf_policy_number` (`policy_number`),
  KEY `idx_pdf_insurance_slug` (`insurance_slug`),
  KEY `idx_pdf_pdf_type_slug` (`pdf_type_slug`),
  KEY `idx_pdf_dir_name` (`dir_name`),
  KEY `idx_pdf_file_name` (`file_name`),
  KEY `idx_pdf_created_at` (`created_at`),
  KEY `idx_pdf_updated_at` (`updated_at`),
  KEY `idx_pdf_moreum_document_id` (`moreum_document_id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `aegon_pdf_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `personal_id_number` varchar(11) COLLATE utf8_unicode_ci NOT NULL,
  `pol_id` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `policy_number` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `insurance_slug` varchar(128) COLLATE utf8_unicode_ci NOT NULL,
  `pdf_type_slug` varchar(128) COLLATE utf8_unicode_ci NOT NULL,
  `dir_name` varchar(128) COLLATE utf8_unicode_ci NOT NULL,
  `file_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `json_data` longtext COLLATE utf8_unicode_ci,
  `json_processed` longtext COLLATE utf8_unicode_ci,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `moreum_document_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pdf_log_personal_id_number` (`personal_id_number`),
  KEY `idx_pdf_pol_id` (`pol_id`),
  KEY `idx_pdf_policy_number` (`policy_number`),
  KEY `idx_pdf_log_insurance_slug` (`insurance_slug`),
  KEY `idx_pdf_log_pdf_type_slug` (`pdf_type_slug`),
  KEY `idx_pdf_log_dir_name` (`dir_name`),
  KEY `idx_pdf_log_file_name` (`file_name`),
  KEY `idx_pdf_log_created_at` (`created_at`),
  KEY `idx_pdf_log_updated_at` (`updated_at`),
  KEY `idx_pdf_moreum_document_id` (`moreum_document_id`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
